version: '3'
networks:
  default:

services:
  mysql:
    # NOTE: Uncomment the line below if you are using Mac with m1/m2 chip
    platform: linux/x86_64
    container_name:  mysql
    image: mysql:5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: gobookstorerest
      MYSQL_USER: sandbox_user
      MYSQL_PASSWORD: passpass
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    networks:
      - default

volumes:
  mysql: